server:
  port: 9999
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/Master_UDC_2022_G4
    username: Master_UDC_2022_G4
    password: 9PVlYwTLPUsA245d!4
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

# oauth2 configuration  
security:
  oauth2:
    client:
      client-id: demo
      client-secret: 8Fjkk59bXKws8bmMNFZB
      authorized-grant-types: password,authorization_code,refresh_code,implicit
      scope: openid
      
demo:
  oauth:
    enabled: true
    accessTokenValiditySeconds: 86400
    refreshTokenValiditySeconds: 86400

    
    
    